jQuery("#mostsmallmob_level").val("<%= @mostsmallmob.level %>")
jQuery("#mostsmallmob_job_level").val("<%= @mostsmallmob.job_level %>")
jQuery("#mostsmallmob_name").val("<%= @mostsmallmob.name %>")
jQuery("#mostsmallmob_gender").attr("checked", <%= @mostsmallmob.gender %>)
jQuery("#mostsmallmob_age").val("<%= @mostsmallmob.age %>")
jQuery("#mostsmallmob_max_hp").val("<%= @mostsmallmob.max_hp %>")
jQuery("#mostsmallmob_max_sp").val("<%= @mostsmallmob.max_sp %>")
jQuery("#mostsmallmob_hp").val("<%= @mostsmallmob.hp %>")
jQuery("#mostsmallmob_sp").val("<%= @mostsmallmob.sp %>")
jQuery("#mostsmallmob_str").val("<%= @mostsmallmob.str %>")
jQuery("#mostsmallmob_dex").val("<%= @mostsmallmob.dex %>")
jQuery("#mostsmallmob_con").val("<%= @mostsmallmob.con %>")
jQuery("#mostsmallmob_int").val("<%= @mostsmallmob.int %>")
jQuery("#mostsmallmob_wis").val("<%= @mostsmallmob.wis %>")
jQuery("#mostsmallmob_cha").val("<%= @mostsmallmob.cha %>")
jQuery("#mostsmallmob_battle_exp").val("<%= @mostsmallmob.battle_exp %>")
jQuery("#mostsmallmob_job_exp").val("<%= @mostsmallmob.job_exp %>")


