class Consts
  NORMAL_MAP_X_SIZE = 10
  NORMAL_MAP_Y_SIZE = 10
  NORMAL_DUNGEON_X_SIZE = 24
  NORMAL_DUNGEON_Y_SIZE = 24
  MAP_PLAIN_SYMBOL = '1'
  MAP_MOUNTAIN_SYMBOL = '2'
  MAP_SEA_SYMBOL = '3'
  RES_IRON_SYMBOL = 'I'
  RES_GOLD_SYMBOL = 'G'
  RES_ANIMAL_SYMBOL = 'A'
  RES_COTTON_SYMBOL = 'C'
  RES_FISH_SYMBOL = 'F'
  CONST_FARM_SYMBOL = 'F'
  CONST_MINE_SYMBOL = 'M'
  CONST_WEPON_STUDIO_SYMBOL = 'W'
  CONST_ARMOR_STUDIO_SYMBOL = 'A'
  CONST_POTION_STUDIO_SYMBOL = 'P'
  CONST_TRAP_STUDIO_SYMBOL = 'T'
  CONST_TRADING_POST_SYMBOL = 'C'
  CONST_PORT_SYMBOL = 'H'
  DUNGEON_BLANK_SYMBOL = '0'
  DUNGEON_COCRETE_SYMBOL = '1'
end