# coding: utf-8

class Mostsmallparams
  END_LINE = 5
  START_LINE = 1
  WARRIOR_JOB_IDS = [1]
  WIZARD_JOB_IDS = [2]
  HEALER_JOB_IDS = [3]
  THIEF_JOB_IDS = [5]
  COUNTER_JOB_IDS = [1, 4]
  WIZARD_RETREAT_HP_RATE = 0.6
  HEALER_RETREAT_HP_RATE = 0.5
  OTHER_RETREAT_HP_RATE = 0.4
  DD_SKILL_CATEGORY_ID = 1
  DOT_SKILL_CATEGORY_ID = 3
  ATTACK_SKILL_CATEGORY_IDS = [DD_SKILL_CATEGORY_ID, DOT_SKILL_CATEGORY_ID]
  HD_SKILL_CATEGORY_ID = 2
  HOT_SKILL_CATEGORY_ID = 4
  HEAL_SKILL_CATEGORY_IDS = [HD_SKILL_CATEGORY_ID, HOT_SKILL_CATEGORY_ID]
  STATUS_UP_SKILL_CATEGORY_ID = 7
  WARRIOR_INITIAL_HATE = 100
  HIT_ADJUST_MAX = 0.3
  DAMAGE_AMPLIFIER = 0.2
  DAMAGE_ADJUST_MAX = 0.8
  DAMAGE_SD = 0.2
  DRAGON_SPECIE_ID = 2
end